# Generated by Django 6.0.6 on 2026-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name'),
        ('employees', '0002_employee_profile_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['joining_date'], name='idx_employee_joining_date'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['salary'], name='idx_employee_salary'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'salary'], name='idx_department_salary'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('salary__gte', 10000)), name='salary_check'),
        ),
    ]
