# Generated by Django 6.0.6 on 2026-06-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_idx_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION check_joining_date()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.joining_date > CURRENT_DATE THEN
                    RAISE EXCEPTION 'Joining date cannot be in the future';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS employee_joining_date_trigger ON employees_employee;
            CREATE TRIGGER employee_joining_date_trigger
            BEFORE INSERT OR UPDATE ON employees_employee
            FOR EACH ROW EXECUTE FUNCTION check_joining_date();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS employee_joining_date_trigger ON employees_employee;
            DROP FUNCTION IF EXISTS check_joining_date();
            """
        )
    ]
